version: '3.8'

services:
  backend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./sessions:/app/sessions
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=backend/server.py
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: >
      bash -c "cd /app && 
      pip install -r backend/requirements.txt &&
      python -m flask run --host=0.0.0.0"
    restart: unless-stopped

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    command: >
      bash -c "cd /app && 
      npm ci &&
      npm run build &&
      npm start"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sessions:
