version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.alpine
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./sessions:/app/sessions
    environment:
      - FLASK_APP=backend/server.py
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.alpine
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sessions:
